name: Scheduled Maintenance

on:
  schedule:
    - cron: "*/5 * * * *"   # runs every 5 minutes
  workflow_dispatch:

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run maintenance script
        run: |
          echo "Performing daily cleanup..."
          npm run cleanup || echo "No cleanup script found"
